version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: rm_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rm_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data